# -*- coding: utf-8 -*-
"""Metadatos editoriales por municipio (textos cualitativos ya aprobados, sin
comparaciones entre municipios). Los datos numéricos vienen de datos/*.json."""

MUNICIPIOS = [
    # nombre (como en el tablero), slug, subregión, acento, bajada
    dict(nombre="Aguadas", slug="aguadas", sub="Norte", acento="#9c7a1e",
         bajada="Café, sombrero de iraca y una población que envejece.",
         econ="Aguadas vive del <b>café</b> y del tejido de la <b>palma de iraca</b>, de donde sale el sombrero aguadeño. Su casco histórico es patrimonio y el Festival Nacional del Pasillo sostiene un turismo cultural activo."),
    dict(nombre="Anserma", slug="anserma", sub="Bajo Occidente", acento="#b5872a",
         bajada="Café y comercio en una villa fundada en 1539.",
         econ="Anserma vive del <b>café</b>, el <b>comercio</b> y la agricultura de ladera. Es centro de servicios para las veredas y los municipios vecinos del bajo occidente."),
    dict(nombre="Aranzazu", slug="aranzazu", sub="Norte", acento="#16887a",
         bajada="La familia que se hizo pequeña.",
         econ="«El Faro del Norte» vivió siempre del café. Hoy el <b>aguacate Hass</b> gana terreno y el <b>fique</b> guarda la memoria de la cultura de la cabuya, en un municipio de comercio y pequeñas empresas."),
    dict(nombre="Belalcázar", slug="belalcazar", sub="Bajo Occidente", acento="#6f8c2f",
         bajada="Café de ladera, coronado por el Cristo Rey.",
         econ="Belalcázar vive del <b>café</b> y la agricultura de ladera, con el monumento a <b>Cristo Rey</b> como emblema. Es un municipio campesino del bajo occidente."),
    dict(nombre="Chinchiná", slug="chinchina", sub="Centro Sur", acento="#6f4a2f",
         bajada="Corazón cafetero de hogares cada vez más pequeños.",
         econ="Chinchiná es <b>epicentro cafetero</b>: allí están Cenicafé y buena parte de la trilla y la industria del café. Está conurbada con Manizales y su economía gira en torno al <b>café</b> y los servicios asociados."),
    dict(nombre="Filadelfia", slug="filadelfia", sub="Alto Occidente", acento="#2f8f6f",
         bajada="Montaña y café que se quedan sin gente joven.",
         econ="Filadelfia vive del <b>café</b>, la <b>caña</b> y la agricultura de montaña. Es un municipio rural del alto occidente del que sale buena parte de su población joven."),
    dict(nombre="La Dorada", slug="ladorada", sub="Magdalena Caldense", acento="#b23a48",
         bajada="Ganado, comercio y calor a orillas del río Magdalena.",
         econ="La Dorada es el <b>centro urbano y logístico</b> del oriente caldense, a orillas del río Magdalena. Vive de la <b>ganadería</b>, el <b>comercio</b>, el transporte y la pesca, y su cruce de vías la hace puerta de la región."),
    dict(nombre="La Merced", slug="lamerced", sub="Alto Occidente", acento="#8a6a4f",
         bajada="Un pueblo pequeño y cafetero que envejece.",
         econ="La Merced es un municipio pequeño, <b>cafetero y agrícola</b>, del alto occidente. Su economía es campesina y su población ha disminuido."),
    dict(nombre="Manizales", slug="manizales", sub="Centro Sur", acento="#3b4ea0",
         bajada="La capital que crece en gente y encanece a la vez.",
         econ="Manizales es la <b>capital del departamento</b>: concentra <b>educación superior</b>, servicios, comercio, industria y el negocio del café. Es el centro administrativo y económico de Caldas."),
    dict(nombre="Manzanares", slug="manzanares", sub="Alto Oriente", acento="#4a7a3a",
         bajada="Café, caña panelera y aguacate en el oriente.",
         econ="Manzanares vive del <b>café</b>, la <b>caña panelera</b> y el <b>aguacate</b>. Es un centro agrícola del oriente caldense."),
    dict(nombre="Marmato", slug="marmato", sub="Alto Occidente", acento="#b07a14",
         bajada="El pueblo del oro, aún con población joven.",
         econ="Marmato es un histórico <b>pueblo minero</b> construido sobre la montaña. Vive del <b>oro</b> y tiene una fuerte identidad pluriétnica."),
    dict(nombre="Marquetalia", slug="marquetalia", sub="Alto Oriente", acento="#5f7f1f",
         bajada="Tierra de café y panela en el oriente caldense.",
         econ="Marquetalia vive del <b>café</b>, la <b>panela</b> y el <b>aguacate</b>, con una economía campesina de ladera."),
    dict(nombre="Marulanda", slug="marulanda", sub="Alto Oriente", acento="#3f7d8c",
         bajada="Un pequeño municipio de páramo que se está quedando solo.",
         econ="Marulanda es un municipio de <b>alta montaña y páramo</b>, frío y disperso. Vive de la <b>ganadería</b>, incluida la cría de ovejas y la lana, de la <b>papa</b> y de la agricultura de altura."),
    dict(nombre="Neira", slug="neira", sub="Centro Sur", acento="#2f6690",
         bajada="Café, panela y una población que vive cada vez más años.",
         econ="A <b>21 km de Manizales</b>, Neira vive del <b>café</b>, la <b>ganadería</b> y la <b>panela</b>, con la arepa de Neira como sello propio."),
    dict(nombre="Norcasia", slug="norcasia", sub="Magdalena Caldense", acento="#2d8ca0",
         bajada="Agua, energía y una población todavía joven.",
         econ="Norcasia vive junto al <b>embalse y la central hidroeléctrica La Miel</b>: energía, pesca y agricultura. Es un municipio joven, creado en 1999."),
    dict(nombre="Palestina", slug="palestina", sub="Centro Sur", acento="#55792e",
         bajada="Café y aeropuerto a las puertas de Manizales.",
         econ="Palestina es tierra <b>cafetera</b> y sede del <b>Aeropuerto del Café</b>. Su cercanía a Manizales y Chinchiná le da un papel logístico y de servicios."),
    dict(nombre="Pensilvania", slug="pensilvania", sub="Alto Oriente", acento="#2e7d5b",
         bajada="Se va la juventud, se queda la vejez.",
         econ="Pensilvania vive del <b>café</b>, la <b>caña panelera</b>, el frijol y el aguacate, con una tradición reconocida de <b>reforestación y madera</b> y de organización comunitaria."),
    dict(nombre="Pácora", slug="pacora", sub="Norte", acento="#9c5a3c",
         bajada="Café y ganadería en un norte que envejece.",
         econ="Pácora vive del <b>café</b> y la <b>ganadería</b> en el norte cafetero de Caldas."),
    dict(nombre="Riosucio", slug="riosucio", sub="Alto Occidente", acento="#b1542a",
         bajada="Una familia que cambia sin perder su raíz.",
         econ="Territorio <b>Embera Chamí</b> con cuatro resguardos y el Carnaval del Diablo, Riosucio vive de la <b>minería de oro</b>, el <b>café</b> y la <b>panela</b>. Buena parte de la vida familiar se organiza dentro de los resguardos."),
    dict(nombre="Risaralda", slug="risaralda", sub="Bajo Occidente", acento="#a0712a",
         bajada="Caña y café en el valle del río Risaralda.",
         econ="Risaralda vive de la <b>caña</b>, el <b>café</b> y la agricultura del valle, con una economía campesina muy ligada a Anserma."),
    dict(nombre="Salamina", slug="salamina", sub="Norte", acento="#a9741a",
         bajada="La Ciudad Luz, patrimonio cafetero que envejece.",
         econ="«La Ciudad Luz», Pueblo Patrimonio del Paisaje Cultural Cafetero, vive del <b>café</b>, la <b>ganadería</b> de San Félix y un <b>turismo cultural</b> en crecimiento."),
    dict(nombre="Samaná", slug="samana", sub="Magdalena Caldense", acento="#3f8060",
         bajada="Café, cacao y bosque en el oriente profundo.",
         econ="Samaná vive del <b>café</b>, el <b>cacao</b> y el bosque. Es un territorio muy rural que se recompone después de años de conflicto armado."),
    dict(nombre="San José", slug="sanjose", sub="Bajo Occidente", acento="#8a6d2f",
         bajada="Un municipio pequeño y muy rural del occidente.",
         econ="San José es un municipio pequeño, <b>cafetero y agrícola</b>, del bajo occidente, con una economía campesina y gran peso rural."),
    dict(nombre="Supía", slug="supia", sub="Alto Occidente", acento="#b05a2e",
         bajada="Minería, caña y mezcla de culturas.",
         econ="Supía vive de la <b>minería</b>, la <b>caña panelera</b> y el <b>comercio</b>. Es un municipio pluriétnico, con comunidades indígenas y afrodescendientes."),
    dict(nombre="Victoria", slug="victoria", sub="Magdalena Caldense", acento="#b0602a",
         bajada="Ganado y pesca a orillas del Magdalena.",
         econ="Victoria vive de la <b>ganadería</b>, la <b>pesca</b> y la agricultura de tierra caliente, a orillas del Magdalena."),
    dict(nombre="Villamaría", slug="villamaria", sub="Centro Sur", acento="#3b6ea0",
         bajada="A los pies del Nevado, creciendo junto a Manizales.",
         econ="Villamaría, conurbada con <b>Manizales</b> y a los pies del <b>Nevado del Ruiz</b>, vive del agro, la floricultura, los servicios y el turismo."),
    dict(nombre="Viterbo", slug="viterbo", sub="Bajo Occidente", acento="#5d7a2e",
         bajada="Crece en gente, envejece a gran velocidad.",
         econ="En el valle del río Risaralda y sobre el eje Pereira, Manizales y Medellín, Viterbo vive de la <b>caña</b>, la <b>ganadería</b> y algo de café. Su ubicación le da potencial logístico y agroindustrial."),
]

# Imágenes ya aprobadas por el usuario: se leen de datos/_meta_actual.json
FOTOS_FIJAS = ("ladorada", "marulanda")
